import Head from "next/head";
import { motion } from "framer-motion";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiOutlineInstagram,
} from "react-icons/ai";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import { Container } from "postcss";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
  
    
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jibanta Nrzary         </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below!
            </p>
            
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
           
            <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                >

           <a   href='https://github.com/jibanta66'
                target='_blank'
                rel='noreferrer'>
                <AiFillGithub />
          </a>
           </motion.button>
                
              <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}>

            <a   href='https://www.linkedin.com/in/jibanta-n-503264209/'
                target='_blank'
                rel='noreferrer'> 
              <AiFillLinkedin /></a>
              </motion.button>

              <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }} >
              <a   href='http://instagram.com/ronal.666?utm_source=qr'
                target='_blank'
                rel='noreferrer'>
                <AiOutlineInstagram /></a>
                </motion.button>
            </div>
            
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-70 md:w-70">
              <Image src={deved} width={100} height={100} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
         
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                  >
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">css,scss,ttailwincss</p>
              <p className="text-gray-800 py-1">framer-moyion</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">ttailwincss</p></motion.button>
            </div>
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                  >
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Dependency Tools I Use</h4>
              <p className="text-gray-800 py-1">next.js</p>
              <p className="text-gray-800 py-1">react </p>
              <p className="text-gray-800 py-1">react-icons</p>
              <p className="text-gray-800 py-1">vercel</p></motion.button>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <motion.button
               whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                  >
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in hire me for your current project? I will be interested in working with you.
              </p>
              <h4 className="py-4 text-teal-600">My contacts</h4>
              <p className="text-gray-800 py-1">linkedin</p>
              <p className="text-gray-800 py-1">Gmail</p>
              <p className="text-gray-800 py-1">Instagram</p>
              <p className="text-gray-800 py-1">PhoneNo</p></motion.button>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming.
            </p>
          </div>
          <div className="nav">
 <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1 ">  
          <div class="container">
          <div class="button-container">
          <span class="mask">
             <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web1}/></button>
                       </div>
                      </div>
              </div>
            <div className="basis-1/3 flex-1">
            <div class="container">
          <div class="button-container">
          <span class="mask">
        <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web2}/></button>
                       </div>
                      </div>
            </div>
            <div className="basis-1/3 flex-1">
            <div class="container">
          <div class="button-container">
          <span class="mask">
        <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web3}/></button>
                       </div>
                      </div>
                      </div>
            <div className="basis-1/3 flex-1">
            <div class="container">
          <div class="button-container">
          <span class="mask">
        <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web4}/></button>
                       </div>
                      </div>
            </div>
            <div className="basis-1/3 flex-1">
            <div class="container">
          <div class="button-container">
          <span class="mask">
        <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web5}/></button>
                       </div>
                      </div>
            </div>
            <div className="basis-1/3 flex-1">
            <div class="container">
          <div class="button-container">
          <span class="mask">
        <Image className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}/></span>

        <button type="button" name="Hover">
          
          <Image className="rounded-lg object-cover"
                layout="responsive"
                src={web6}/></button>
                </div>
                       </div>
                      </div>
            </div>
          </div>
        </section>
      </main>
    </div>
   
  );
}
